### ISSUE TITLE
Dockerfile generated by GridGain Console 

### ISSUE THREAD

**Issue by ghost** [gridgain/docker#1]
I'm trying to create project using GridGain console. The following is the generate Dockerfile content
```
# Start from GridGain Professional image.
FROM gridgain/gridgain-pro:2.1.2
...
```
I'm unable to find the version 2.1.2

**Comment by nva** [comment]
Hi Shan11812,

I uploaded latest version of docker images, please retry

**Comment by ghost** [comment]
Its working now, thanks.
